\newlabel{fig:event_series}
\newlabel{fig:exp_setup}
\newlabel{fig:hr_freq}
\newlabel{fig:len_dist}
\newlabel{fig:norm_fa_score}
\newlabel{fig:norm_t_score}
\newlabel{fig:scaled_sigmoid}
\newlabel{fig:time_dist}
\newlabel{fig:time_dist}
\newlabel{fig:week_freq}
\newlabel{sub@fig:hr_freq}
\newlabel{sub@fig:week_freq}
\newlabel{table:notations}
\newlabel{table:vocab_exp}
\newlabel{table:web20}
\newlabel{tbl:bin_eval}
\newlabel{tbl:diff_eval}
\newlabel{tbl:diff}
\newlabel{tbl:full_eval}
\newlabel{tbl:par_tune_comb}
\newlabel{tbl:par_tune_content}
\newlabel{tbl:par_tune_decay}
\newlabel{tbl:par_tune_dt}
\newlabel{tbl:par_tune_learning}
\newlabel{top_modeling}
